import { DEFAULT_LOCAL_ROOT, DEFAULT_MODEL, DEFAULT_TRAE_APP_NAME } from "@/lib/constants";
import type { TaskItem, TaskRecord, UserSettings, WorkspaceProject } from "@/lib/types";

export const taskRecords: TaskRecord[] = [
  {
    uid: "UID-001",
    recordId: "rec_mock_001",
    traeSessionId: "trae_conv001.001",
    round: 1,
    userPrompt: "为订单系统增加批量退款审核流，并补充异常状态展示。",
    taskType: "功能开发",
    businessDomain: "电商订单",
    modifyScope: "多模块",
    taskCompleted: "是",
    processSatisfaction: "满意",
    unsatisfiedReason: "",
    githubUrl: "https://github.com/example/solo-order-refund",
    branchOrFolder: "main",
    screenshots: "round-1/screenshots",
    screenshotAttachments: [],
    screenshotFileToken: "",
    screenshotExtra: "",
    logs: "round-1/logs.txt",
    qcStatus: "待质检",
    syncStatus: "synced",
    updatedAt: "2026-05-15 14:00",
  },
  {
    uid: "UID-002",
    recordId: "rec_mock_002",
    traeSessionId: "",
    round: 1,
    userPrompt: "",
    taskType: "待分配",
    businessDomain: "待分配",
    modifyScope: "待分配",
    taskCompleted: "未开始",
    processSatisfaction: "未开始",
    unsatisfiedReason: "",
    githubUrl: "",
    branchOrFolder: "",
    screenshots: "",
    screenshotAttachments: [],
    screenshotFileToken: "",
    screenshotExtra: "",
    logs: "",
    qcStatus: "未提交",
    syncStatus: "draft",
    updatedAt: "2026-05-15 14:10",
  },
];

export const taskItems: TaskItem[] = [
  {
    taskId: "TASK-001",
    uidBinding: "UID-002",
    title: "库存预警策略优化",
    promptContent: "请为库存管理系统增加按仓库和商品维度的预警策略，并补充前端配置入口。",
    promptMode: "append",
    model: DEFAULT_MODEL,
    taskType: "功能开发",
    businessDomain: "库存管理",
    modifyScope: "多模块",
    sourceType: "generated",
    status: "ready",
    createdAt: "2026-05-15 14:20",
  },
  {
    taskId: "TASK-002",
    uidBinding: "UID-001",
    title: "订单退款审核流",
    promptContent: "为订单系统增加批量退款审核流，并补充异常状态展示。",
    promptMode: "append",
    model: DEFAULT_MODEL,
    taskType: "功能开发",
    businessDomain: "电商订单",
    modifyScope: "多模块",
    sourceType: "synced",
    status: "submitted",
    submittedAt: "2026-05-15 14:00",
    createdAt: "2026-05-15 13:40",
  },
];

export const workspaceProjects: WorkspaceProject[] = [
  {
    workspaceId: "WS-001",
    taskId: "TASK-002",
    recordId: "rec-002",
    uid: "UID-001",
    repoName: "solo-order-refund",
    githubOwner: "example",
    githubUrl: "https://github.com/example/solo-order-refund",
    localPath: `${DEFAULT_LOCAL_ROOT}/solo-order-refund`,
    currentBranch: "main",
    metadataPath: `${DEFAULT_LOCAL_ROOT}/solo-order-refund/.auto-solo.json`,
    visibility: "private",
    cloneEnabled: true,
    traeOpened: true,
    traeAppName: DEFAULT_TRAE_APP_NAME,
    status: "success",
    createdAt: "2026-05-15 13:45",
  },
];

export const userSettings: UserSettings = {
  feishuAppId: "",
  feishuAppSecret: "",
  feishuRedirectUri: "http://localhost:3000/api/auth/feishu/callback",
  feishuBaseUrl: "https://bcnrsnl3m9wk.feishu.cn/base/HO1Kb3JQpa9e0WsHhQ0c2dpLnYb?table=tblfVRXx3qotQ4mO&view=vewKdKoVia",
  sessionSecret: "replace-with-a-long-random-secret",
  githubOwner: "example",
  repoVisibility: "public",
  cloneEnabled: true,
  openTraeEnabled: true,
  localRoot: DEFAULT_LOCAL_ROOT,
  traeAppName: DEFAULT_TRAE_APP_NAME,
  modelProvider: "openai_compatible",
  modelBaseUrl: "https://api.openai.com/v1",
  modelApiPath: "/chat/completions",
  model: DEFAULT_MODEL,
  modelKey: "",
  dashboardMetricCardOrder: ["task-records", "empty-session", "task-bank", "workspace-projects"],
  dashboardActionCardOrder: ["sync-feishu", "generate-tasks", "submit-feishu", "github-auth", "workspace-create"],
};
